route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'prometheus_alerts_discord'
receivers:
  - name: 'prometheus_alerts_discord'
    webhook_configs:
      - url: 'https://discord.com/api/webhooks/xxxxxxxxxxxxxxxxxxxxxxx'