global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

rule_files:
  - /etc/prometheus/rules/*.rules

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - localhost:9093

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets:
          - 'localhost:9093'

  - job_name: 'node'
    scrape_interval: 5s
    static_configs:
      - targets:
          - 'prometheus.homelab.lan:9100'
          - 'saltmaster.homelab.lan:9100'
